SCompassTrack:
  general:
    radius: '200'
    lang: fr
    prefix: '&e[SCT] '
    userightclicktotrackplayer: true
    useworldwhitelist: false
    worldwhitelist: ''
    pluginactivatedonotherworld: true
  lang:
    fr:
      noplayer: '&3Aucun joueur proche de vous.'
      nopermission: '&3Vous n''avez pas la permission.'
      spawntarget: '&3Votre boussole pointe vers le spawn.'
      playertarget: '&3Votre boussole pointe vers : &2@ptarget &3à  &2@d &3blocs d''ici.'
      incorrectworld: '&3La boussole n''est pas autorisé dans ce monde.'
    en:
      noplayer: '&3No player near you.'
      nopermission: '&3You don''t have permission.'
      spawntarget: '&3Your compass is pointing to the spawn.'
      playertarget: '&3Your compass is pointing to : &2@ptarget &3at &2@d &3block.'
      incorrectworld: '&3Compass is not allowed in this world.'
